# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: Home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - thor_Art1_Yaw
    - thor_Art2_Pitch
    - thor_Art3_Pitch
    - thor_Art4_Yaw
    - thor_Art5_Pitch
    - thor_Art6_Yaw
    - thor_finger1_prismatic
    - thor_finger2_prismatic
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - thor_Art1_Yaw
      - thor_Art2_Pitch
      - thor_Art3_Pitch
      - thor_Art4_Yaw
      - thor_Art5_Pitch
      - thor_Art6_Yaw
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - thor_finger1_prismatic
      - thor_finger2_prismatic