joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

arm_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - thor_Art1_Yaw
      - thor_Art2_Pitch
      - thor_Art3_Pitch
      - thor_Art4_Yaw
      - thor_Art5_Pitch
      - thor_Art6_Yaw

    constraints:
      goal_time: &goal_time_constraint 0.1
      stopped_velocity_tolerance: 0.01
      thor_Art1_Yaw:
        goal: &goal_pos_constraint 0.02 # Uno 1% de error en un goal de pi/2
        trajectory: &trajectory_pos_constraint 0.05
      thor_Art2_Pitch:
        goal: *goal_pos_constraint
        trajectory: *trajectory_pos_constraint
      thor_Art3_Pitch:
        goal: *goal_pos_constraint
        trajectory: *trajectory_pos_constraint
      thor_Art4_Yaw:
        goal: *goal_pos_constraint
        trajectory: *trajectory_pos_constraint
      thor_Art5_Pitch:
        goal: *goal_pos_constraint
        trajectory: *trajectory_pos_constraint
      thor_Art6_Yaw:
        goal: *goal_pos_constraint
        trajectory: *trajectory_pos_constraint

    gains:
      thor_Art1_Yaw: {p: 1000, i: 0, d: 5, i_clamp: 100}

      thor_Art2_Pitch: {p: 2000, i: 1000, d: 5, i_clamp: 7, antiwindup: true}

      thor_Art3_Pitch: {p: 100, i: 1000, d: 5, i_clamp: 7, antiwindup: true}

      thor_Art4_Yaw: {p: 200, i: 10, d: 1, i_clamp: 1, antiwindup: true}

      thor_Art5_Pitch: {p: 20, i: 10, d: 0, i_clamp: 5, antiwindup: true}

      thor_Art6_Yaw: {p: 100, i: 10, d: 0, i_clamp: 10, antiwindup: true}	


gripper_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - thor_finger1_prismatic 
      - thor_finger2_prismatic
    gains: # Required because we're controlling an effort interface
      thor_finger1_prismatic : {p: 300,  d: 0.1, i: 10, i_clamp: 0.25, antiwindup: true}
      thor_finger2_prismatic : {p: 300,  d: 0.1, i: 10, i_clamp: 0.25, antiwindup: true}    
      
