joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

gripper_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - finger1_prismatic 
      - finger2_prismatic
    gains: # Required because we're controlling an effort interface
      finger1_prismatic : {p: 300,  d: 0.1, i: 10, i_clamp: 0.25, antiwindup: true}
      finger2_prismatic : {p: 300,  d: 0.1, i: 10, i_clamp: 0.25, antiwindup: true}  

base_controller:
    type: effort_controllers/JointPositionController
    joint: base_prismatic
    pid: {p: 100, i: 13, d: 5, i_clamp: 10}
      


#    gains: # Required because we're controlling an effort interface
#      finger1_prismatic : {p: 10000,  d: 0, i: 1000, i_clamp: 1}
#      finger2_prismatic: {p: 10000,  d: 0, i: 1000, i_clamp: 1}
